services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

  api:
    build: ./api
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://mongo:27017/weather
      PLACE_NAME: "Bangkok, TH"
      TIMEZONE: "Asia/Bangkok"
    ports: ["4000:4000"]
    depends_on: [mongo]

  fetcher:
    build: ./fetcher
    restart: "no"
    environment:
      MONGO_URL: mongodb://mongo:27017/weather
      PLACE_NAME: "Bangkok, TH"
      LAT: "13.7563"
      LON: "100.5018"
      TIMEZONE: "Asia/Bangkok"
      PROVIDER_USER_AGENT: "WeatherMicro/1.0 (contact: you@example.com)"
      RUN_ONCE: "true"
    depends_on: [mongo]

  web:
    build: ./web
    restart: unless-stopped
    ports: ["3000:3000"]
    depends_on: [api]

volumes:
  mongo_data:
